package cn.ggx.entity;

import java.util.Date;

/**
 * course_video
 * 
 * @author bianj
 * @version 1.0.0 2021-01-21
 */
public class CourseVideo implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 276078872201196969L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** videoName */
    private String videoName;

    /** flag */
    private Integer flag;

    /** freeFlag */
    private Integer freeFlag;

    /** topicId */
    private Integer topicId;

    /** playUrl */
    private String playUrl;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取videoName
     * 
     * @return videoName
     */
    public String getVideoName() {
        return this.videoName;
    }

    /**
     * 设置videoName
     * 
     * @param videoName
     */
    public void setVideoName(String videoName) {
        this.videoName = videoName;
    }

    /**
     * 获取flag
     * 
     * @return flag
     */
    public Integer getFlag() {
        return this.flag;
    }

    /**
     * 设置flag
     * 
     * @param flag
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 获取freeFlag
     * 
     * @return freeFlag
     */
    public Integer getFreeFlag() {
        return this.freeFlag;
    }

    /**
     * 设置freeFlag
     * 
     * @param freeFlag
     */
    public void setFreeFlag(Integer freeFlag) {
        this.freeFlag = freeFlag;
    }

    /**
     * 获取topicId
     * 
     * @return topicId
     */
    public Integer getTopicId() {
        return this.topicId;
    }

    /**
     * 设置topicId
     * 
     * @param topicId
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * 获取playUrl
     * 
     * @return playUrl
     */
    public String getPlayUrl() {
        return this.playUrl;
    }

    /**
     * 设置playUrl
     * 
     * @param playUrl
     */
    public void setPlayUrl(String playUrl) {
        this.playUrl = playUrl;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}