package cn.ggx.entity;

import java.util.Date;

/**
 * order
 * 
 * @author bianj
 * @version 1.0.0 2021-01-21
 */
public class Order implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -8589730374799258087L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** userId */
    private Integer userId;

    /** commodityPrice */
    private Double commodityPrice;

    /** flag */
    private Integer flag;

    /** commodityName */
    private String commodityName;

    /** orderFlag */
    private Integer orderFlag;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取userId
     * 
     * @return userId
     */
    public Integer getUserId() {
        return this.userId;
    }

    /**
     * 设置userId
     * 
     * @param userId
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * 获取commodityPrice
     * 
     * @return commodityPrice
     */
    public Double getCommodityPrice() {
        return this.commodityPrice;
    }

    /**
     * 设置commodityPrice
     * 
     * @param commodityPrice
     */
    public void setCommodityPrice(Double commodityPrice) {
        this.commodityPrice = commodityPrice;
    }

    /**
     * 获取flag
     * 
     * @return flag
     */
    public Integer getFlag() {
        return this.flag;
    }

    /**
     * 设置flag
     * 
     * @param flag
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }

    /**
     * 获取commodityName
     * 
     * @return commodityName
     */
    public String getCommodityName() {
        return this.commodityName;
    }

    /**
     * 设置commodityName
     * 
     * @param commodityName
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    /**
     * 获取orderFlag
     * 
     * @return orderFlag
     */
    public Integer getOrderFlag() {
        return this.orderFlag;
    }

    /**
     * 设置orderFlag
     * 
     * @param orderFlag
     */
    public void setOrderFlag(Integer orderFlag) {
        this.orderFlag = orderFlag;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}