package cn.ggx.entity;


import java.util.Date;

/**
 * user
 * 
 * @author bianj
 * @version 1.0.0 2021-01-21
 */
public class User implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 3861128625290449210L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    private Integer id;

    /** email */
    private String email;

    /** password */
    private String password;

    /** mobile */
    private String mobile;

    /** vipFlag */
    private Integer vipFlag;

    /** createTime */
    private Date createTime;

    /* This code was generated by TableGo tools, mark 1 end. */

    /* This code was generated by TableGo tools, mark 2 begin. */

    public User() {
    }

    public User(String email, String password, String mobile, Integer vipFlag, Date createTime) {
        this.email = email;
        this.password = password;
        this.mobile = mobile;
        this.vipFlag = vipFlag;
        this.createTime = createTime;
    }

    public User(Integer id, String email, String password, String mobile, Integer vipFlag, Date createTime) {
        this.id = id;
        this.email = email;
        this.password = password;
        this.mobile = mobile;
        this.vipFlag = vipFlag;
        this.createTime = createTime;
    }

    /**
     * 获取id
     * 
     * @return id
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * 设置id
     * 
     * @param id
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * 获取email
     * 
     * @return email
     */
    public String getEmail() {
        return this.email;
    }

    /**
     * 设置email
     * 
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * 获取password
     * 
     * @return password
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * 设置password
     * 
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * 获取mobile
     * 
     * @return mobile
     */
    public String getMobile() {
        return this.mobile;
    }

    /**
     * 设置mobile
     * 
     * @param mobile
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * 获取vipFlag
     * 
     * @return vipFlag
     */
    public Integer getVipFlag() {
        return this.vipFlag;
    }

    /**
     * 设置vipFlag
     * 
     * @param vipFlag
     */
    public void setVipFlag(Integer vipFlag) {
        this.vipFlag = vipFlag;
    }

    /**
     * 获取createTime
     * 
     * @return createTime
     */
    public Date getCreateTime() {
        return this.createTime;
    }

    /**
     * 设置createTime
     * 
     * @param createTime
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", email='" + email + '\'' +
                ", password='" + password + '\'' +
                ", mobile='" + mobile + '\'' +
                ", vipFlag=" + vipFlag +
                ", createTime=" + createTime +
                '}';
    }

    /* This code was generated by TableGo tools, mark 2 end. */
}